import os

TENANT_ID = os.getenv("TENANT_ID")

CLIENT_ID = os.getenv("CLIENT_ID")

CLIENT_SECRET = os.getenv("CLIENT_SECRET")

SITE_ID = os.getenv("SITE_ID")

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")

AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")

AZURE_AI_ENDPOINT = os.getenv("AZURE_AI_ENDPOINT")

AZURE_AI_KEY = os.getenv("AZURE_AI_KEY")